### ISSUE TITLE
Remove Bootstrap dependency for BlazorUI

### ISSUE THREAD

**Issue by StardustDL** [StardustDL/modulight#59]
Bootstrap css may conflict with AntDesign css.

Now uses 3 css in bootstrap:

```css
.text-center {
    text-align: center!important;
}

.p-0 {
    padding: 0!important;
}

.p-1 {
    padding: .25rem!important;
}

@media (min-width: 1400px)
.container, .container-lg, .container-md, .container-sm, .container-xl, .container-xxl {
    max-width: 1320px;
}
@media (min-width: 1200px)
.container, .container-lg, .container-md, .container-sm, .container-xl {
    max-width: 1140px;
}
@media (min-width: 992px)
.container, .container-lg, .container-md, .container-sm {
    max-width: 960px;
}
@media (min-width: 768px)
.container, .container-md, .container-sm {
    max-width: 720px;
}
@media (min-width: 576px)
.container, .container-sm {
    max-width: 540px;
}
.container, .container-fluid, .container-lg, .container-md, .container-sm, .container-xl, .container-xxl {
    width: 100%;
    padding-right: var(--bs-gutter-x,.75rem);
    padding-left: var(--bs-gutter-x,.75rem);
    margin-right: auto;
    margin-left: auto;
}
```
